# Generated by Django 4.0.6 on 2022-07-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School_details',
            fields=[
                ('Sid', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='School ID')),
                ('S_name', models.CharField(max_length=50, verbose_name='School Name')),
                ('S_loc', models.CharField(max_length=150, verbose_name='School Address')),
                ('S_logo', models.ImageField(upload_to='logo', verbose_name='School Logo')),
                ('S_moto', models.CharField(blank=True, max_length=150, verbose_name='School Moto or Description')),
                ('S_tel1', models.CharField(max_length=15, verbose_name='Contact Number1')),
                ('S_tel2', models.CharField(blank=True, max_length=15, verbose_name='Contact Number2')),
                ('S_tel3', models.CharField(blank=True, max_length=15, verbose_name='Contact Number3')),
            ],
            options={
                'verbose_name': 'School Detail',
                'db_table': 'school',
            },
        ),
    ]
