# Generated by Django 4.0.6 on 2022-07-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Subject Code')),
                ('name', models.CharField(max_length=10, verbose_name='Subject Name')),
            ],
            options={
                'verbose_name': 'Subject',
                'db_table': 'subjects',
            },
        ),
    ]
