# Generated by Django 4.0.6 on 2022-07-28 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('school', '0003_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='CT',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='staff.staff', verbose_name='Class Teacher'),
        ),
    ]
