# Generated by Django 4.0.6 on 2022-07-28 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0004_alter_classes_ct'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('father_fname', models.CharField(max_length=15, verbose_name="Father's First Name")),
                ('father_lname', models.CharField(max_length=15, verbose_name="Father's Last Name")),
                ('mother_fname', models.CharField(max_length=15, verbose_name="Mother's First Name")),
                ('mother_lname', models.CharField(max_length=15, verbose_name="Mother's Last Name")),
                ('father_con', models.CharField(max_length=13, verbose_name="Father's Contact Number")),
                ('mother_con', models.CharField(max_length=13, verbose_name="Mother's Contact Number")),
                ('father_alter', models.CharField(blank=True, max_length=13, verbose_name="Father's Alternate Number")),
                ('mother_alter', models.CharField(blank=True, max_length=13, verbose_name="Mother's Alternate Number")),
                ('father_prof', models.CharField(max_length=50, verbose_name="Father's Profession")),
                ('mother_prof', models.CharField(max_length=50, verbose_name="Mother's Profession")),
                ('father_img', models.ImageField(upload_to='image', verbose_name="Father's Image")),
                ('mother_img', models.ImageField(upload_to='image', verbose_name="Mother's Image")),
                ('f_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=('F', 'Female'), max_length=1, verbose_name='Sex')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('address', models.CharField(max_length=150)),
                ('contact1', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('contact2', models.CharField(blank=True, max_length=15, verbose_name='Alternate Number')),
                ('from_date', models.DateTimeField(auto_now=True, verbose_name='Date From')),
                ('stid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Student ID')),
                ('study_in', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='school.classes', verbose_name='Current Class')),
            ],
            options={
                'verbose_name_plural': 'Students',
                'db_table': 'student',
            },
        ),
    ]
