# Generated by Django 4.0.6 on 2022-07-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_to_date_alter_student_from_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECA',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Activity Code')),
                ('name', models.CharField(max_length=10, verbose_name='Activity Name')),
                ('year', models.DateField(auto_now_add=True, verbose_name='Year of Event')),
                ('s_date', models.DateTimeField(verbose_name='Start Date')),
                ('e_date', models.DateTimeField(verbose_name='End Date')),
            ],
            options={
                'verbose_name_plural': 'Extra Curricular activities',
                'db_table': 'ECA',
                'unique_together': {('name', 'year')},
            },
        ),
    ]
